// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjU9SKWRZLaXB5HrKLQ2aC0RH7p-KY_8',
    appId: '1:399621253660:web:d259bcabbd1b3c358ecdd9',
    messagingSenderId: '399621253660',
    projectId: 'todoapp-5d755',
    authDomain: 'todoapp-5d755.firebaseapp.com',
    storageBucket: 'todoapp-5d755.appspot.com',
    measurementId: 'G-8FNRMBZRLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pPhWF_3RbaRFIX0Q--n_qY4n2W_psnM',
    appId: '1:399621253660:android:1aaebf7128c837518ecdd9',
    messagingSenderId: '399621253660',
    projectId: 'todoapp-5d755',
    storageBucket: 'todoapp-5d755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEY8VZTq0Gdd33J7qX9njO0PgqjNP-z4g',
    appId: '1:399621253660:ios:fd100589efdde4788ecdd9',
    messagingSenderId: '399621253660',
    projectId: 'todoapp-5d755',
    storageBucket: 'todoapp-5d755.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEY8VZTq0Gdd33J7qX9njO0PgqjNP-z4g',
    appId: '1:399621253660:ios:559a631a64e6d50b8ecdd9',
    messagingSenderId: '399621253660',
    projectId: 'todoapp-5d755',
    storageBucket: 'todoapp-5d755.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
